### ISSUE TITLE
Update README.

### ISSUE THREAD

**Issue by ajantha-bhat** [Wuerike/docker-iceberg-kafka-connect#1]
https://github.com/Wuerike/kafka-iceberg-streaming/tree/main#spark-iceberg

> You can open the jupyter lab at http://localhost:8888/lab/tree/notebooks and use the sample notebook to query the table

I think we should also mention that we need to have jupyter notebook installed for this.

**Comment by Wuerike** [comment]
This refers to the jupyter instance from the `tabulario/spark-iceberg` image

You can check the port 8888 is exposed in the docker compose file
https://github.com/Wuerike/kafka-iceberg-streaming/blob/9d525355969a8f867603e542b366e1892a1bbd09/docker-compose.yaml#L190

**Comment by ajantha-bhat** [comment]
oh, But the link provided in readme was not working for me. 

Also, now I did make down and make up again, I am getting this error 

> kafka-iceberg-streaming-console-1  | {"level":"error","ts":"2023-11-07T17:15:23.805Z","msg":"Sending REST error","topic_name":"payments","route":"/api/topics/payments/configuration","method":"GET","status_code":404,"remote_address":"172.22.0.1:59688","public_error":"Could not fetch topic config because the requested topic 'payments' does not exist.","error":"the requested topic does not exist"}


I am following these sequence of operation 
-  make up
-  make produce
-  make down

**Comment by ajantha-bhat** [comment]
Never mind it works. 

a) I might have checked UI before spark is up.
b) Previous tear down was not proper which was causing problem for `kafka-iceberg-streaming-console-1`

**Comment by ajantha-bhat** [comment]
we can probably add the diagram like below for easy understanding 

<img width="1230" alt="image" src="https://github.com/Wuerike/kafka-iceberg-streaming/assets/5889404/95cf3fc8-e1c2-4686-92b0-ca532a140f7c">

**Comment by Wuerike** [comment]
Thanks @ajantha-bhat!

**Comment by ajantha-bhat** [comment]
I think now the connector supports auto creation of iceberg tables via `iceberg.tables.auto-create-enabled`
Maybe we can simplify the demo without those spark/create_table.py script

**Comment by Wuerike** [comment]
It may work, I just prefer the script for 2 reasons:
1. Better control over data types and any table settings such as partitioning 
2. Demonstrate to people they can run scripts
